name: 'Run Pest'
description: 'Run PHP Pest tests'

runs:
  using: "composite"
  steps:
    - name: Run Pest
      id: pest
      shell: bash
      #language=bash
      run: |
        mkdir -p var/test-results
        vendor/bin/pest --ci --log-junit var/test-results/junit.xml
      continue-on-error: true # So the test results are always published

    - name: Publish Test Results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: var/test-results/junit.xml

    - name: Fail Job if Tests Failed
      if: steps.pest.outcome == 'failure'   # pre-continue outcome
      shell: bash
      #language=bash
      run: exit 1
