name: 'Run Pest'
description: 'Run PHP Pest tests'

runs:
  using: "composite"
  steps:
    - name: Cache PHPStan
      uses: actions/cache@v4
      with:
        path:         var/cache/phpstan
        key:          phpstan-${{ hashFiles('phpstan.dist.neon') }}-${{ hashFiles('composer.json') }}
        restore-keys: phpstan-

    - name: Run PHPStan
      id:   phpstan
      shell: bash
      #language=bash
      run: vendor/bin/phpstan

#      - name: Run PHPStan
#        uses: GeneaLabs/action-reviewdog-phpstan@1.1.2
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          reporter: github-pr-review
#          phpstan_level: 8
#          fail_on_error: true
