name: Quality

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  checks:        write
  contents:      read
  issues:        read
  pull-requests: write

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP and Install Composer Packages
        uses: ./.github/actions/setup

      - name: Cache PHPStan
        uses: actions/cache@v4
        with:
          path:         var/cache/phpstan
          key:          phpstan-${{ hashFiles('phpstan.dist.neon') }}-${{ hashFiles('composer.json') }}
          restore-keys: phpstan-

      - name: Run PHPStan
        id:   phpstan
        shell: bash
        #language=bash
        run: vendor/bin/phpstan
