name: Test Suite

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents:      read
  pull-requests: write

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP and Install Composer Packages
        uses: ./.github/actions/setup

      - name: Run PHPStan
        uses: ./.github/actions/static-analysis

  unit-tests:
    name:    Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP and Install Composer Packages
        uses: ./.github/actions/setup
        with:
          php-version: ${{ matrix.php-version }}

      - name: Run Unit Tests
        uses: ./.github/actions/unit-tests
